# Generated by Django 3.2.7 on 2022-01-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrral_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='COLLEGE_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='P_HOSTEL_NAME',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='REFRRED_BY',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
