# Generated by Django 4.1.7 on 2023-02-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refrral_form', '0002_auto_20220102_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='AREA_OF_HOSTEL',
        ),
        migrations.RemoveField(
            model_name='form',
            name='COLLEGE_ID',
        ),
        migrations.RemoveField(
            model_name='form',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='form',
            name='P_HOSTEL_NAME',
        ),
        migrations.RemoveField(
            model_name='form',
            name='REFRRED_BY',
        ),
        migrations.RemoveField(
            model_name='form',
            name='WHATSAPP',
        ),
        migrations.RemoveField(
            model_name='form',
            name='YEAR',
        ),
    ]
